version: "3.8"

services:

  db:
    image: postgres:16-alpine
    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data


  auth-service:
    build: ./auth-service

    container_name: auth-service

    env_file:
      - ./auth-service/.env

    ports:
      - "3001:3001"

    depends_on:
      - db



  expense-service:
    build: ./expense-service

    container_name: expense-service

    env_file:
      - ./expense-service/.env

    ports:
      - "3002:3002"

    depends_on:
      - db



  report-service:
    build: ./report-service

    container_name: report-service

    env_file:
      - ./report-service/.env

    environment:
      PORT: 3003
      EXPENSE_SERVICE: http://expense-service:3002

    ports:
      - "3003:3003"

    depends_on:
      - expense-service



  nginx:
    image: nginx:latest

    container_name: nginx-gateway

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - auth-service
      - expense-service
      - report-service



volumes:
  postgres-data: