events {}
http {
server {
listen 80;
location /api/auth/ {
proxy_pass http://auth-service:3001/;
}
location /api/expenses/ {
proxy_pass http://expense-service:3002/;
}
location /api/reports/ {
proxy_pass http://report-service:3003/;
}
}
}